stages:
    - build
    - test


variables:
    SYLIUS_BUILD_DIR: etc/build

build:backend:
    image: composer:1
    stage: build
    cache:
        key: ${CI_JOB_NAME}
        paths:
            - node_modules
    script:
        - composer require "symfony/symfony:^4.1" --no-interaction --no-update
        - composer validate --strict
        - composer install --no-progress --classmap-authoritative --ignore-platform-reqs --no-interaction
        - (cd tests/Application && bin/console cache:warmup --env=test -vvv)
    artifacts:
        paths:
            - vendor
            - bin
            - node_modules
        expire_in: 1 hour

.build:fronentd:
    image: ??
    script:
        - (cd tests/Application && bin/console assets:install web --env=test -vvv)
        - (cd tests/Application && yarn build)
        - (cd tests/Application && yarn install)

test:code:
    stage: test
    image: php:7.2-alpine
    script:
        - bin/phpstan.phar analyse -c phpstan.neon -l max src
        - bin/ecs
    dependencies:
        - build:backend


test:tests:
    stage: test
    image: php:7.2-alpine
    before_script:
        - (cd tests/Application && bin/console doctrine:database:create --env=test -vvv)
        - (cd tests/Application && bin/console doctrine:schema:create --env=test -vvv)
    script:
        - bin/phpunit
    artifacts:
        when: on_failure
        paths:
            - ${SYLIUS_BUILD_DIR}/*.log
    dependencies:
        - build:backend
