stages:
    - build
    - test

build:3.4:backend:
    image: composer:1
    stage: build
    cache:
        key: ${CI_JOB_NAME}
        paths:
            - vendor
    script:
        - composer require "symfony/symfony:^3.4" --no-interaction --no-update
        - composer install --no-progress --classmap-authoritative --ignore-platform-reqs --no-interaction
    artifacts:
        paths:
            - vendor
            - bin
        expire_in: 1 hour


build:4.1:backend:
    image: composer:1
    stage: build
    cache:
        key: ${CI_JOB_NAME}
        paths:
            - vendor
    script:
        - composer require "symfony/symfony:^4.1" --no-interaction --no-update
        - composer install --no-progress --classmap-authoritative --ignore-platform-reqs --no-interaction
    artifacts:
        paths:
            - vendor
            - bin
        expire_in: 1 hour
