stages:
    - build
    - test


variables:
    SYLIUS_BUILD_DIR: etc/build

.build:backend: &buildBackend
    image: composer:1
    stage: build
    cache:
        key: ${CI_JOB_NAME}
        paths:
            - node_modules
    script:
        - composer validate --strict
        - composer install --no-progress --classmap-authoritative --ignore-platform-reqs --no-interaction
        - (cd tests/Application && bin/console assets:install web --env=test -vvv)
        - (cd tests/Application && bin/console cache:warmup --env=test -vvv)
        - (cd tests/Application && yarn build)
        - (cd tests/Application && yarn install)
    artifacts:
        paths:
            - vendor
            - bin
            - node_modules
        expire_in: 1 hour

build:3.4:backend:
    <<: *buildBackend
    before_script:
        - composer require "symfony/symfony:^3.4" --no-interaction --no-update

build:4.1:backend:
    <<: *buildBackend
    before_script:
        - composer require "symfony/symfony:^4.1" --no-interaction --no-update

test:3.4:code:
    stage: test
    image: php:7.2-alpine
    script:
        - bin/phpstan.phar analyse -c phpstan.neon -l max src
        - bin/ecs

test:3.4:tests:
    stage: test
    image: php:7.2-alpine
    before_script:
        - (cd tests/Application && bin/console doctrine:database:create --env=test -vvv)
        - (cd tests/Application && bin/console doctrine:schema:create --env=test -vvv)
    script:
        - bin/phpunit
    dependencies:
        - build:3.4:backend

    artifacts:
        when: on_failure
        paths:
            - ${SYLIUS_BUILD_DIR}/*.log
