stages:
    - build
    - test

variables:
    SYLIUS_BUILD_DIR: etc/build
    COMPOSER_HOME: tmp/composer
    APP_ENV: test
    APP_SECRET: 2a2f0c6cf200b9b9ff6f33fceabb8643
    DATABASE_URL: pgsql://runner:runner-password@localhost:5432/test-db
    MAILER_URL: null://localhost
    POSTGRES_DB: test-db
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: runner-password

build:backend:
    image: composer:1
    stage: build
    cache:
        key: ${CI_JOB_NAME}
        paths:
            - vendor
            - node_modules
            - ${COMPOSER_HOME}
    script:
        - composer require "symfony/symfony:^4.1" --no-interaction --no-update
        - composer validate --strict
        - composer install --no-progress --classmap-authoritative --ignore-platform-reqs --no-interaction
        - (cd tests/Application && bin/console cache:warmup --env=test -vvv)
        - (cd tests/Application && bin/console assets:install public --env=test -vvv)
    artifacts:
        paths:
            - vendor
            - node_modules
            - tests/Application
        expire_in: 1 hours

.build:fronentd:
    image: ??
    script:
        - (cd tests/Application && yarn build)
        - (cd tests/Application && yarn install)

test:code:
    stage: test
    image: php:7.2
    script:
        - bin/phpstan.sh
        - bin/ecs.sh
    dependencies:
        - build:backend

test:tests:
    services:
        - postgres:10-alpine
    stage: test
    image: 831119889470.dkr.ecr.eu-central-1.amazonaws.com/mangoweb/php:7.2 #TODO Create image for public
    script:
        - (cd tests/Application && bin/console doctrine:schema:create --env=test -vvv)
        - bin/phpunit
        - bin/behat --tags="~@javascript" --strict -vvv --no-interaction || bin/behat --tags="~@javascript" --strict -vvv --no-interaction --rerun
    artifacts:
        when: always
        paths:
            - ${SYLIUS_BUILD_DIR}
            - tests/Application/var/log
    dependencies:
        - build:backend

test:selenium:
    services:
        - postgres:10-alpine
        - selenium/standalone-chrome:2.53.1
    stage: test
    image: 831119889470.dkr.ecr.eu-central-1.amazonaws.com/mangoweb/php:7.2 #TODO Create image for public
    script:
        - (cd tests/Application && bin/console doctrine:schema:create --env=test -vvv)
        - (cd tests/Application && bin/console server:start 127.0.0.1:8080 -d public -e test)
        - bin/behat --tags="@javascript" --strict -vvv --no-interaction || bin/behat --tags="@javascript" --strict -vvv --no-interaction --rerun
    after_script:
        - (cd tests/Application && bin/console server:stop)
    artifacts:
        when: always
        paths:
            - ${SYLIUS_BUILD_DIR}
            - tests/Application/var/log
    dependencies:
        - build:backend
