services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Sylius\Component\Channel\Context\ChannelContextInterface: "@sylius.context.channel.cached"
    MangoSylius\PaymentFeePlugin\Model\Calculator\DelegatingCalculatorInterface: '@MangoSylius\PaymentFeePlugin\Model\Calculator\DelegatingCalculator'
    MangoSylius\PaymentFeePlugin\Form\Type\Calculator\FlatRateConfigurationType: ~

    MangoSylius\PaymentFeePlugin\Model\Calculator\DelegatingCalculator:
        arguments:
            $registry: '@mango-sylius.registry.payment_calculator'

    MangoSylius\PaymentFeePlugin\Form\Type\CalculatorChoiceType:
        arguments:
            $calculators: '%mango-sylius.payment_fee_calculators%'
        tags:
            - {name: form.type}

    MangoSylius\PaymentFeePlugin\Form\Extension\PaymentMethodTypeExtension:
        arguments:
            $calculatorRegistry: "@mango-sylius.registry.payment_calculator"
            $formTypeRegistry: "@mango-sylius.form_registry.payment_calculator"
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\PaymentBundle\Form\Type\PaymentMethodType }

    MangoSylius\PaymentFeePlugin\Form\Extension\PaymentMethodChoiceTypeExtension:
        arguments:
            $calculatorRegistry: "@mango-sylius.registry.payment_calculator"
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\PaymentBundle\Form\Type\PaymentMethodChoiceType }

    mango-sylius.registry.payment_calculator:
        class: Sylius\Component\Registry\ServiceRegistry
        arguments:
            $className: MangoSylius\PaymentFeePlugin\Model\Calculator\CalculatorInterface
            $context: payment fee calculator

    mango-sylius.form_registry.payment_calculator:
        class: Sylius\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry


    mango-sylius.payment_fee_calculator:
        class: MangoSylius\PaymentFeePlugin\Model\Calculator\DelegatingCalculator
        arguments:
            $registry: "@mango-sylius.registry.payment_calculator"

    MangoSylius\PaymentFeePlugin\Model\Calculator\FlatRateCalculator:
        tags:
            - {name: mango-sylius.payment_fee_calculator, calculator: flat_rate, form_type: "MangoSylius\\PaymentFeePlugin\\Form\\Type\\Calculator\\ChannelBasedFlatRateConfigurationType", label: "mango-sylius.form.payment_calculator.flat_rate_configuration.label"}

    MangoSylius\PaymentFeePlugin\Model\PaymentChargesProcessor:
        arguments:
            $adjustmentFactory: "@sylius.factory.adjustment"
        tags:
            - {name: sylius.order_processor, priotiry: 0}

    sylius.order_processing.order_payment_processor.checkout:
        class: Sylius\Component\Core\OrderProcessing\OrderPaymentProcessor
        arguments:
            - "@sylius.order_payment_provider"
        tags:
            - {name: sylius.order_processor, priotiry: 5}

    app.block_event_listener.admin.layout.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@MangoSyliusPaymentFeePlugin/Admin/_javascripts.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.layout.javascripts, method: onBlockEvent }
